project:
  type: website
  title: "Introduction to Machine Learning with Python"
  output-dir: "_site"
  
website:
  title: "Introduction to Machine Learning with Python"
  description: "A comprehensive one-day course covering essential ML libraries: Scikit-learn, Keras, PyTorch, and TensorFlow"
  site-url: "https://your-site-url.com"
  repo-url: "https://github.com/jfimbett/TemplateCourse"
  
  navbar:
    title: "ML with Python"
    left:
      - text: "Home"
        href: index.html
      - text: "Course Materials"
        menu:
          - text: "Day 1: Scikit-learn"
            href: src/lectures/day1-scikit-learn/index.html
          - text: "Day 1: Keras"
            href: src/lectures/day1-keras/index.html
          - text: "Day 1: PyTorch"
            href: src/lectures/day1-pytorch/index.html
          - text: "Day 1: TensorFlow"
            href: src/lectures/day1-tensorflow/index.html
    right:
      - icon: github
        href: "https://github.com/jfimbett/TemplateCourse"

format:
  html:
    theme: 
      - cosmo
      - src/assets/styles.css # where custom styles are located
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    code-fold: false
    code-tools: true
    citations-hover: true
    footnotes-hover: true
    
  revealjs:
    theme: white
    css: src/assets/styles.css
    highlight-style: github
    slide-number: true
    chalkboard: true
    preview-links: auto
    transition: slide
    background-transition: fade
    hash-type: number
    controls: true
    progress: true
    center: false
    
execute:
  freeze: auto
  cache: true

editor: visual
